name: promptbind
channels:
  - pyg
  - pytorch
  - nvidia
  - milagraph
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas=2.2.3
  - pytorch=2.4.1
  - pytorch-cuda=12.1
  - torchaudio=2.4.1
  - torchvision=0.19.1
  - python-lmdb
  - torchmetrics
  - scipy=1.13.1
  - pytorch-scatter
  - rdkit=2024.03.6
  - accelerate
  - scikit-learn
  - pymol-open-source
  - torchdrug
  - conda-forge::tensorboard
  - pip
  - pip:
      - -f https://data.pyg.org/whl/torch-2.4.0+cu121.html
      - torch-geometric

