name: promptbind
channels:
  - pyg
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas
  - pytorch
  - pytorch-cuda=12.4
  - torchaudio
  - torchvision
  - python-lmdb
  - torchmetrics
  - scipy
  - pytorch-scatter
  - rdkit
  - accelerate
  - conda-forge::tensorboard
  - pip
  - pip:
      - torch-geometric==2.6.1

