config:
  data_path: "data/pdbbind2020"
  pocket_prompt_nf: 8
  complex_prompt_nf: 8
  ckpt: "results/PromptBind-8/best-model/model.safetensors"
  batch_size: 4
  resultFolder: "./results"
  exp_name: "test_prompt_8"
  n_iter: 12

#### The following arguments are not recommended for modification
args:
  mode: 5
  data: "0"
  seed: 600
  gs_tau: 1
  gs_hard: false
  restart: null
  reload: null
  addNoise: "5"
  use_y_mask: false
  use_equivalent_native_y_mask: false
  use_affinity_mask: 0
  affinity_loss_mode: 1
  pred_dis: 1
  posweight: 8
  relative_k: 0.01
  relative_k_mode: 0
  label: "baseline"
  use_whole_protein: false
  tqdm_interval: 0.1
  lr: 0.0001
  pocket_coord_huber_delta: 3.0
  coord_loss_function: "SmoothL1"
  coord_loss_weight: 1.0
  pair_distance_loss_weight: 1.0
  pair_distance_distill_loss_weight: 1.0
  pocket_cls_loss_weight: 1.0
  pocket_distance_loss_weight: 0.05
  pocket_cls_loss_func: "bce"
  use_compound_com_cls: true
  compound_coords_init_mode: "pocket_center_rdkit"
  trig_layers: 1
  distmap_pred: "mlp"
  mean_layers: 4
  inter_cutoff: 10.0
  intra_cutoff: 8.0
  refine: "refine_coord"
  coordinate_scale: 5.0
  geometry_reg_step_size: 0.001
  lr_scheduler: "constant"
  add_attn_pair_bias: true
  explicit_pair_embed: true
  opm: false
  add_cross_attn_layer: true
  rm_layernorm: true
  keep_trig_attn: false
  pocket_radius: 20.0
  rm_LAS_constrained_optim: false
  rm_F_norm: false
  norm_type: "per_sample"
  noise_for_predicted_pocket: 0.0
  test_random_rotation: false
  random_n_iter: true
  clip_grad: true
  sample_n: 0
  fix_pocket: false
  pocket_idx_no_noise: true
  ablation_no_attention: false
  ablation_no_attention_with_cross_attn: false
  redocking: false
  redocking_no_rotate: false
  pocket_pred_layers: 1
  pocket_pred_n_iter: 1
  use_esm2_feat: true
  center_dist_threshold: 4.0
  mixed_precision: "no"
  disable_tqdm: false
  log_interval: 50
  optim: "adamw"
  warmup_epochs: 15
  total_epochs: 400
  disable_validate: true
  disable_tensorboard: false
  hidden_size: 512
  weight_decay: 0.01
  stage_prob: 0.25
  pocket_pred_hidden_size: 128
  post_optim: null
  post_optim_mode: 0
  post_optim_lr: 1
  post_optim_epoch: 1000
  post_optim_lbfgs_iter: 100
  rigid: false
  local_eval: true
  train_ligand_torsion_noise: false
  train_pred_pocket_noise: 0.0
  esm2_concat_raw: false